//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseSite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int ID { get; set; }
        public string CourseName { get; set; }
        public string CourseDescription { get; set; }
        public Nullable<int> Price { get; set; }
        public int Duration { get; set; }
        public int CategoryID { get; set; }
        public string Instructor { get; set; }
    }
}
